In [2]:
import math
import numpy as np
import pandas as pd
from simanneal import Annealer

# 4
Gegeven volgende te maximaliseren doelfunctie:
Met volgende beperkingen: -1.0 ≤ xi ≤ 1.0 met i=1,2
Zoek een goede oplossing.

In [3]:
class OptimalisatieProblem(Annealer):
    def energy(self):
        x1 = self.state[0]
        x2 = self.state[1]
        sum = 0.2 + self.state[0]**2 + self.state[1]**2
        sum = sum - 0.1 * math.cos(6*math.pi*x1) -0.1 * math.cos(6*math.pi*x2) 
        return -sum    # + voor minimum - voor maximum

    def move(self):
        i = np.random.randint(0,2)
        self.state[i] += np.random.normal(0, 0.1)
        self.state[i] = np.clip(self.state[i], -1, 1)

# minimum = 0 in (0,0)
init_sol =  np.random.uniform(-1,1, size=2) #initial solution: array met 2 elementen
opdracht=OptimalisatieProblem(init_sol)
# set annealing parameters, if not default values will be used
opdracht.Tmax = 25000.0 
opdracht.Tmin = 2.5 
opdracht.updates = 1000
opdracht.steps = 100000
opt_sol = opdracht.anneal()
print(opt_sol)

 Temperature        Energy    Accept   Improve     Elapsed   Remaining
    2.50000         -1.14   100.00%    50.00%     0:00:02     0:00:00

(array([-1.,  1.]), -2.0)


# 2
Je bent belast met het ontwerp van dakgoten waarbij de productiekost zo laag mogelijk moet zijn.
Daarom is het noodzakelijk dat de dakgoten een zo optimale doorsnede hebben met het beschikbare
materiaal zodat bladeren en vuil makkelijk afgevoerd kunnen worden. Het bedrijf waarvoor je werkt
koopt metalen platen aan die een breedte hebben van 1m. M.a.w. H + B + H -zie tekening- moet kleiner
of gelijk zijn aan 1m. Bepaal de ideale breedte B en hoogte H van de dakgoot die
je uit de platen van 1m kan maken.

In [4]:
# class OptimalisatieProblem(Annealer):
#     def energy(self):
#         b = self.state[0]
#         sum = b * ((1 - b)/2)
#         return -sum    # + voor minimum - voor maximum
# 
#     def move(self):
#         i = 0
#         self.state[i] += np.random.normal(0, 0.1)
#         self.state[i] = np.clip(self.state[i], 0, 1)
# init_sol =  np.random.uniform(0,1, size=1) #initial solution: array met 1 elementen
# opdracht=OptimalisatieProblem(init_sol)
# # set annealing parameters, if not default values will be used
# opdracht.Tmax = 25000.0 
# opdracht.Tmin = 2.5 
# opdracht.updates = 1000
# opdracht.steps = 100000
# opt_sol = opdracht.anneal()
# print(opt_sol)

Vraag 2: De dakgoten
Je bent belast met het ontwerp van dakgoten waarbij de productiekost zo laag mogelijk moet zijn.
Daarom is het noodzakelijk dat de dakgoten een zo optimale doorsnede hebben met het beschikbare
materiaal zodat bladeren en vuil makkelijk afgevoerd kunnen worden. Het bedrijf waarvoor je werkt
koopt metalen platen aan die een breedte hebben van 1m. M.a.w. H + B + H -zie tekening- moet kleiner
of gelijk zijn aan 1m. Bepaal de ideale breedte B en hoogte H van de dakgoot die
je uit de platen van 1m kan maken.

In [46]:
class optimalisatie(Annealer):
    def energy(self):
        b = self.state[0]
        sum = b * ((1 - b)/2)
        return -sum 
        
        
    def move(self):
        
        self.state[0] += np.random.normal(0,0.1)
        self.state[0] = np.clip(self.state[0],0,1)
    
initial = np.random.normal(0,1, size=1)
optimise = optimalisatie(initial)
opt = optimise.anneal()
print(opt)  

 Temperature        Energy    Accept   Improve     Elapsed   Remaining


(array([0.49998491]), -0.12499999988619961)


# 1
Je bevindt je in een geheime kamer die uitgerust is met een deur met tijdslot. Je ziet een timer aftellen
die meldt dat je nog maar vijf minuten over het alvorens de deur voor altijd op slot zal zijn. Voor je neus
liggen waardevolle voorwerpen met elk hun eigen opbrengst en gewicht. Je hebt een rugzak bij die een
absoluut maximaal gewicht kan torsen van 750gr. Op Canvas vind je de lijst van voorwerpen met hun
gewicht en opbrengst. Stel de optimale rugzak samen. Je zou op een optimale opbrengst van 1458
moeten uitkomen (of toch zeker een waarde dicht daarbij in de buurt).

In [47]:
data = pd.read_csv("../DataSets/Knapsack Items.csv")
# data
class OptimalisatieProblem(Annealer):
    def energy(self):
        list = self.state
        sum = (list * value).sum()
        if (list * weight).sum() > 750:
            sum = 0
        
        return -sum    # + voor minimum - voor maximum

    def move(self):
        i = np.random.randint(0,len(self.state))
        self.state[i] = not self.state[i]
        # self.state[i] = np.clip(self.state[i], 0, 1)
weight=data['gewichten(gr)']
value=data.waarde
init_sol =  np.random.uniform(0,2,size=len(data)) #initial solution: array met 1 elementen
opdracht=OptimalisatieProblem(init_sol)
# set annealing parameters, if not default values will be used
opdracht.Tmax = 25000.0 
opdracht.Tmin = 2.5 
opdracht.updates = 1000
opdracht.steps = 100000
opt_sol = opdracht.anneal()
print(opt_sol)

 Temperature        Energy    Accept   Improve     Elapsed   Remaining
    2.50000      -1379.00     0.00%     0.00%     0:00:16     0:00:00

(array([1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1.]), -1458.0)


# Vraag 3: Het voetbalstadion
De plaatselijke sportclub wil een nieuw stadion bouwen. De
omtrek van het sportveld moet 400m bedragen, en tegelijkertijd
willen we ervoor zorgen dat het centrale middenveld een maximale
oppervlakte heeft. Bepaal de ideale lengte –en
breedteverhouding.

In [7]:
class voetbalProblem(Annealer):
    def energy(self):
        l = self.state[0]
        b= (400 - 2 * l)/ math.pi 
        sum =  b * l
        return - sum    # + voor minimum - voor maximum

    def move(self):
        i=0
        self.state[i] += np.random.normal(0, 0.1)
        self.state[i] = np.clip(self.state[i], 0, 200)
init_sol =  np.random.uniform(0,200, size=1) #initial solution: array met 1 elementen
opdracht=voetbalProblem(init_sol)
# set annealing parameters, if not default values will be used
opdracht.Tmax = 25000.0 
opdracht.Tmin = 2.5 
opdracht.updates = 1000
opdracht.steps = 100000
opt_sol = opdracht.anneal()
print(opt_sol)

 Temperature        Energy    Accept   Improve     Elapsed   Remaining


(array([99.99994362]), -6366.19772367379)
