# P4W4: Meta-heuristieken

In [2]:
import math
import numpy as np
import pandas as pd
from simanneal import Annealer

## 1. Simulated Annealing

In [3]:
class RastriginProblem(Annealer):
    def energy(self):
        x1 = self.state[0]
        x2 = self.state[1]
        sum = 10 * 2 + self.state[0]**2 + self.state[1]**2
        sum = sum - 10 * math.cos(2 * math.pi * self.state[0]) - 10 * math.cos(2 * math.pi * self.state[1])
        return sum    # + want minimum

    def move(self):
        i = np.random.randint(0,2)
        self.state[i] += np.random.normal(0, 0.1)
        self.state[i] = np.clip(self.state[i], -5.12, 5.12)

# minimum = 0 in (0,0)
init_sol =  np.random.uniform(-5.12,5.12, size=2) #initial solution: array met 2 elementen
rastrigin=RastriginProblem(init_sol)
# set annealing parameters, if not default values will be used
rastrigin.Tmax = 25000.0 
rastrigin.Tmin = 2.5 
rastrigin.updates = 10
rastrigin.steps = 100000
opt_sol = rastrigin.anneal()
print(opt_sol)

 Temperature        Energy    Accept   Improve     Elapsed   Remaining


(array([-0.00565418,  0.01110969]), 0.03081856783441239)


## 2. Traveling Salesman

In [77]:
# distance_matrix = np.array([[0, 100, 125, 100,  75],
#                             [100, 0,  50,  75, 100],
#                             [125, 50,  0, 100, 125],
#                             [100, 75, 100,   0, 50],
#                             [75, 100, 125,  50,  0]]) 
import numpy as np

# Set the random seed for reproducibility
np.random.seed(42)

# Number of nodes
n = 15

# Generate a random upper triangular matrix
random_distances = np.random.randint(1, 200, size=(n, n))

# Make the matrix symmetric
distance_matrix = (random_distances + random_distances.T) / 2

# Ensure diagonal elements are zero
np.fill_diagonal(distance_matrix, 0)

# Convert to integer
distance_matrix = distance_matrix.astype(int)

print("Generated 15x15 distance matrix for TSP:")
print(distance_matrix)


Generated 15x15 distance matrix for TSP:
[[  0 166  91  33  99  63 135  54  87 126  85  66 123 126 102]
 [166   0  99  94  56  97 134  83  71  96 160  41 141  58  67]
 [ 91  99   0  95 188   9 121 163 168  97 101 146  41  91 157]
 [ 33  94  95   0 183  36  78  76  46  78  76 112 121 145  82]
 [ 99  56 188 183   0  99 164  87  64 133 110  66 126  49 160]
 [ 63  97   9  36  99   0 116 121 170  20  62  38  65 185  76]
 [135 134 121  78 164 116   0  88 109  76  40  86  46  92   5]
 [ 54  83 163  76  87 121  88   0 100  24  68  24  72  45 132]
 [ 87  71 168  46  64 170 109 100   0 131 132  59 195 143 114]
 [126  96  97  78 133  20  76  24 131   0  97 104 109  74  69]
 [ 85 160 101  76 110  62  40  68 132  97   0 138  82  39 149]
 [ 66  41 146 112  66  38  86  24  59 104 138   0  95  65 168]
 [123 141  41 121 126  65  46  72 195 109  82  95   0  90 149]
 [126  58  91 145  49 185  92  45 143  74  39  65  90   0 121]
 [102  67 157  82 160  76   5 132 114  69 149 168 149 121   0]]


In [92]:
class TravellingSalesmanProblem(Annealer):
    def move(self):
        """Swaps two cities in the route."""
        a = np.random.randint(0, len(self.state) - 1)
        b = np.random.randint(0, len(self.state) - 1)
        self.state[a], self.state[b] = self.state[b], self.state[a]
        
    def energy(self):
        """Calculates the length of the route."""
        dist = 0
        for i in range(len(self.state)):
            dist += distance_matrix[self.state[i - 1], self.state[i]]
        return dist

initial_state = np.random.permutation(n)

print("\nInitial state (random permutation of cities):")
print(initial_state)
tsp = TravellingSalesmanProblem(initial_state)
tsp.Tmax = 25000.0 
tsp.Tmin = 2.5 
tsp.updates = 10
tsp.steps = 100000
route, distance = tsp.anneal()
route, distance



 Temperature        Energy    Accept   Improve     Elapsed   Remaining



Initial state (random permutation of cities):
[11 10  3  1 14  7 12  9  2  0  4  6  5  8 13]


(array([ 4, 12,  2,  5,  9,  7,  0,  3,  8, 11,  1, 14,  6, 10, 13]), 653)